'use strict';
// the successful actions' name have to end with '_SUCCESS'
// so that they decrease the ongoing ajax calls' number
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

// =================

export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILED = 'DELETE_ALERT_FAILED';
export const BUSY_ALERT_STARTED = 'BUSY_ALERT_STARTED';

export const ADD_CITY_STARTED = 'ADD_CITY_STARTED';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const ADD_CITY_FAILED = 'ADD_CITY_CANCELLED';

export const LOAD_ALERTLIST_SUCCESS = 'LOAD_ALERTLIST_SUCCESS';
export const LOAD_ALERTLIST_FAILED = 'LOAD_ALERTLIST_FAILED';

export const LOAD_SEARCHCITIES_STARTED = 'LOAD_SEARCHCITIES_STARTED';
export const LOAD_SEARCHCITIES_SUCCESS = 'LOAD_SEARCHCITIES_SUCCESS';
export const LOAD_SEARCHCITIES_FAILED = 'LOAD_SEARCHCITIES_FAILED';

export const AUTH_LOGIN_STARTED = 'AUTH_LOGIN_STARTED';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
export const AUTH_LOGOUT_STARTED = 'AUTH_LOGOUT_STARTED';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED';
